spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/birdwatching
spring.datasource.username=birduser
spring.datasource.password=birdpass
spring.jpa.hibernate.ddl-auto=update